/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/utils.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/ProcessData.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/SplitData.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/GenerateLabel.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/StatisticSampleDistribution.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/Classify.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/DrawImportance.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/AddClassifyPredict.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/CalculateWeightedLoss.py
/home/zjy/.conda/envs/zjy/bin/python /mnt/hd0/DeepChecker_code/DrawClassify.py
